Video resizing
RightpointLabs/i-know-you pull request #1
Opened 2018-08-29 18:40 UTC by Jarrett-Long

- Full screen mode is available
- Video resizes on window.resize 
- Shortened timeout rate.  It seems to recognize faces more quickly when the timeout is shorter.

2018-08-29 20:58 UTC, brbarnett commented on web/app.js
> +            }, 300);
Can we keep this 3000 for now? I don't want to overload the API

2018-08-29 21:10 UTC, brbarnett requested changes
The video loads on my screen but it does not track my face

2018-08-30 13:52 UTC, Jarrett-Long commented on web/app.js
> +            }, 300);
Yeah sure thing.  I've added a commit to change it back to 3000.

2018-08-30 15:30 UTC, Jarrett-Long commented
I've committed a tweak that stops and re-initializes the tracker task after window resizing.  Before, the boxing would not properly surround a face after adjusting the screen size.  

I've also noticed that it's much better at recognizing a face when the tracker.setStepSize() value is lowered.

2018-08-30 15:33 UTC, jorupp commented
If there are values that are useful to tinker with for testing, it maybe helpful to have inputs on the page somewhere to specify them.

2018-09-01 12:03 UTC, brbarnett commented on web/app.css
> +    margin: auto 1% 1% auto;
Haven't seen this before (1%). What's it do?

2018-09-01 12:04 UTC, brbarnett approved these changes
Thanks for your help

2018-09-01 12:05 UTC, merged